name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build for Linux (amd64)
      run: go build -v -ldflags="-s -w" -o hhnwifid_linux_amd64
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0

    - name: Build for Linux/iSH (i386)
      run: go build -v -ldflags="-s -w" -o hhnwifid_linux_i386
      env:
        GOOS: linux
        GOARCH: 386
        CGO_ENABLED: 0
        
    - name: Build for Linux (arm64)
      run: go build -v -ldflags="-s -w" -o hhnwifid_linux_arm64
      env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 0
        
    - name: Build for Windows (amd64)
      run: go build -v -ldflags="-s -w" -o hhnwifid_windows_amd64.exe
      env:
        GOOS: windows
        GOARCH: amd64
        
    - name: Build for macOS (amd64)
      run: go build -v -ldflags="-s -w" -o hhnwifid_macos_amd64
      env:
        GOOS: darwin
        GOARCH: amd64
    
    - name: Build for macOS (arm64)
      run: go build -v -ldflags="-s -w" -o hhnwifid_macos_arm64
      env:
        GOOS: darwin
        GOARCH: arm64

    - name: Upload the builds
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: hhnwifid_*
        retention-days: 30
